global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'gradio-app'
    static_configs:
      - targets: ['gradio-app:8000']
    metrics_path: '/metrics'
    scheme: 'http'
    scrape_interval: 5s
    scrape_timeout: 4s